### ISSUE TITLE
Destruction of the anti-spam manifest

### ISSUE THREAD

**Issue by ghost** [ge0rg/jabber-spam-fighting-manifesto#22]
In its current form, the anti-spam manifest does not bring the benefits fight of anti-spam.
A number of users have expressed concern that the anti-spam manifest may be a tool to block objectionable servers

**Comment by ge0rg** [comment]
I'm not really sure what you are trying to say, especially:

- what's the problem?
- what is the goal of this issue?

**Comment by licaon-kter** [comment]
@E-404 Some links could help.

**Comment by ghost** [comment]
The problem is that the manifest is negatively perceived by most users.  The manifest does not force the use of phone numbers - but users think that the manifest forces.  The manifest does not force others the servers to be blocked, but users think it forces.

If most people have a negative attitude towards the manifest, then maybe it should be deleted?

You can conduct a survey on your own to make sure of a negative attitude.

**Comment by licaon-kter** [comment]
Are you sure spam brings happiness?

The negative attitude should be against spam itself not some text on Github. 

People should use better translation services if "for example" is not understood.

**Comment by ge0rg** [comment]
There is a long-form rationale for the blocking in this hard-to-find place: 

https://github.com/JabberSPAM/jabber-spam-fighting-manifesto/blob/master/Freedom-and-Anonymity.md

Please let me know which of your users' perception is not adequately addressed in there.
